# Generated by Django 4.2.7 on 2023-12-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_alter_userdetail_total_orders_completed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdetail", options={"verbose_name": "Customer"},
        ),
    ]
