# Generated by Django 4.2.7 on 2023-12-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '__first__'),
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(editable=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('complete_cost', models.FloatField(default=0)),
                ('discounts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.discount')),
                ('list_of_products', models.ManyToManyField(blank=True, to='products.product')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.userdetail')),
            ],
        ),
    ]
