# Generated by Django 4.2.7 on 2023-12-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_price',
            new_name='unit_price',
        ),
    ]
