# Generated by Django 4.2.7 on 2023-12-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_product_price_orderitem_unit_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_price',
            new_name='item_price',
        ),
    ]
