# Generated by Django 4.2.7 on 2023-12-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_unit_price_orderitem_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete_cost',
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
