# Generated by Django 4.2.7 on 2023-12-17 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_discount_percentage'),
        ('orders', '0010_alter_order_discounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discounts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.discount'),
        ),
    ]
