# Generated by Django 4.2.7 on 2023-12-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brands',
            field=models.ManyToManyField(blank=True, to='products.brand'),
        ),
        migrations.AddField(
            model_name='category',
            name='categories',
            field=models.ManyToManyField(blank=True, to='products.category'),
        ),
    ]
