# Generated by Django 4.2.7 on 2023-12-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_remove_categories_list_of_brands_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='products_list',
        ),
        migrations.AddField(
            model_name='supplier',
            name='list_of_products',
            field=models.ManyToManyField(related_name='Supplier', to='products.product'),
        ),
    ]
