# Generated by Django 4.2.7 on 2023-12-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.FloatField(),
        ),
    ]
