# Generated by Django 4.2.7 on 2023-12-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_supplier_products_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='list_of_categories',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='list_of_brands',
            new_name='brands',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='list_of_brands',
            new_name='brands',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='list_of_categories',
            new_name='categories',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='list_of_products',
        ),
        migrations.RemoveField(
            model_name='category',
            name='list_of_products',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='list_of_products',
        ),
        migrations.AddField(
            model_name='brand',
            name='products',
            field=models.ManyToManyField(related_name='brands', to='products.product'),
        ),
        migrations.AddField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(related_name='categories', to='products.product'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(related_name='suppliers', to='products.product'),
        ),
    ]
