# Generated by Django 4.2.7 on 2023-12-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_list_of_categories_brand_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='products',
            field=models.ManyToManyField(null=True, related_name='brands', to='products.product'),
        ),
        migrations.AlterField(
            model_name='category',
            name='products',
            field=models.ManyToManyField(null=True, related_name='categories', to='products.product'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(null=True, related_name='suppliers', to='products.product'),
        ),
    ]
